'use strict';
const $=id=>document.getElementById(id);let reports=[],repairs=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=n=>new Date(n).toLocaleString('en-GB',{timeZone:'Europe/London'});
function render(){const q=$('report-query').value.trim().toLowerCase(),status=$('report-status').value,list=reports.filter(r=>(!q||`${r.title} ${r.channel} ${r.url}`.toLowerCase().includes(q))&&(!status||r.status===status));$('report-list').innerHTML=list.map(r=>{const index=reports.indexOf(r);return `<article class="source-card"><div><h3>${esc(r.title)}</h3><p class="source-meta">${esc(r.channel)} · ${esc(r.status)} · ${r.reports} failure reports · ${r.viewers} viewer sessions</p><p>${esc(r.reason)}</p><p class="source-note">First ${stamp(r.first_seen)} · Latest ${stamp(r.last_seen)} UK</p><details><summary>Source link</summary><p class="report-url">${esc(r.url)}</p>${r.replacement?`<p>Replacement: ${esc(r.replacement)}</p>`:''}</details><label>Replacement direct Archive video<input type="url" id="replacement-${index}" value="${esc(r.replacement||'')}" placeholder="https://archive.org/download/…/episode.mp4"></label><label>Repair note<input type="text" maxlength="500" id="note-${index}" value="${esc(r.note||'')}" placeholder="What was checked or changed"></label><p class="repair-result" id="result-${index}" role="status"></p></div><div class="source-actions"><a href="${esc(r.replacement||r.url)}" target="_blank" rel="noopener noreferrer">TEST VIDEO</a><button data-action="replaced" data-index="${index}">SAVE REPLACEMENT</button><button data-action="quarantined" data-index="${index}">HOLD SOURCE</button><button data-action="restored" data-index="${index}">RESTORE AFTER CHECK</button></div></article>`;}).join('')||'<p>No matching source reports.</p>';$('report-message').textContent=`${reports.length} saved reports · ${list.length} shown`;$('export-reports').disabled=false;}
async function load(){if(globalThis.BOOTLEG_HOSTING?.backend===false){document.querySelector('.library-header p').textContent='This edition skips failed sources for your current TV visit.';document.querySelector('.library-controls').hidden=true;document.querySelector('.source-actions').hidden=true;$('report-message').textContent='Shared source reports need server hosting. Failed sources are skipped for your current TV visit.';return;}try{$('report-message').textContent='Loading source reports…';const r=await fetch('/api/health',{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();reports=data.reports||[];repairs=data.repairs||[];render();}catch{$('report-message').textContent='Source reports unavailable. Refresh to try again.';}}
$('report-list').addEventListener('click',async e=>{const button=e.target.closest('button[data-action]');if(!button)return;const index=Number(button.dataset.index),r=reports[index],result=$('result-'+index),replacement=$('replacement-'+index).value.trim(),note=$('note-'+index).value;button.disabled=true;result.textContent='Saving…';try{const response=await fetch('/api/repair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:r.url,status:button.dataset.action,replacement,note})});const body=await response.json();if(!response.ok)throw Error(body.error||'Save failed');result.textContent='Saved';await load();}catch(err){result.textContent=err.message+' · your input has been kept.';}finally{button.disabled=false;}});
$('report-query').addEventListener('input',render);$('report-status').addEventListener('change',render);$('refresh-reports').addEventListener('click',load);
$('export-reports').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),reports,repairs},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='bootleg-source-reports.json';a.click();URL.revokeObjectURL(url);});
load();
