(function(root){
'use strict';
const monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];
const labels={'halloween':'Halloween / spooky','christmas':'Christmas','winter':'Winter / snow','valentine':'Valentine’s Day','romance':'Romance','st-patrick':'St Patrick’s / Irish','easter':'Easter','spring':'Spring','paranormal':'Paranormal','ghosts':'Ghosts','cryptids':'Cryptids','ufos':'UFOs','horror':'Horror','thanksgiving':'Thanksgiving','new-year':'New Year','hanukkah':'Hanukkah','kwanzaa':'Kwanzaa','earth-day':'Earth / Arbor Day','mother-day':'Mother’s Day','father-day':'Father’s Day','independence-day':'Independence Day','lunar-new-year':'Lunar New Year','summer':'Summer','back-to-school':'Back to school','april-fools':'April Fools’','snow':'Snow','autumn':'Autumn','mystery':'Mystery'};
const holidayRules={'christmas':'December · Christmas Eve, Christmas Day and Boxing Day spotlights','valentine':'14 February','st-patrick':'17 March','easter':'Easter Sunday · date changes each year','thanksgiving':'US Thanksgiving · fourth Thursday of November','new-year':'31 December and 1 January'};
function holidayPlacement(p){return (p.holiday_events||[]).map(event=>(labels[event]||event)+': '+(holidayRules[event]||'')).join(' · ');}
function archiveURL(term,scope='all'){const value=String(term).trim().replace(/["\\]/g,' ');const phrase='"'+value+'"';const query='mediatype:movies AND '+(scope==='title'?'title:('+phrase+')':phrase);const u=new URL('https://archive.org/search');u.searchParams.set('query',query);return u.href;}
function filterProgrammes(programmes,{query='',channel='',tag='',month='',language='',status=''}={}){const text=query.trim().toLowerCase();return programmes.filter(p=>(!text||[p.title,p.show,p.filename,p.archive_identifier,...(p.seasonal_tags||[])].join(' ').toLowerCase().includes(text))&&(!channel||(p.channels||[p.channel]).includes(channel))&&(!tag||(p.seasonal_tags||[]).includes(tag))&&(!month||(p.schedule_months||[]).includes(Number(month)))&&(!language||p.language_status===language)&&(!status||p.catalogue_status===status));}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
root.BootlegSources={archiveURL,filterProgrammes,holidayPlacement};
if(typeof document==='undefined')return;
const $=id=>document.getElementById(id);let programmes=[],filtered=[],visible=40;let flags={};try{flags=JSON.parse(localStorage.getItem('bootleg.source.flags')||'{}');}catch{}const isHeld=p=>p.broadcast_held||Boolean(flags[p.url]);
function render(){filtered=filterProgrammes(programmes,{query:$('library-query').value,channel:$('library-channel').value,tag:$('library-tag').value,month:$('library-month').value,language:$('library-language').value,status:$('library-status').value});const shown=filtered.slice(0,visible);$('source-count').textContent=`${filtered.length} programme${filtered.length===1?'':'s'} · showing ${shown.length}`;$('source-results').innerHTML=shown.length?shown.map(p=>`<article class="source-card"><div><h3>${esc(p.title)}</h3><p class="source-meta">${esc((p.channels||[p.channel]).join(' / '))} · ${esc(p.type)}${p.duration_seconds?' · '+Math.round(p.duration_seconds/60)+' min':''}${p.daypart==='Evening'?' · Evening':''}</p><p class="source-note">${esc(p.language_label||'Language not yet verified')} · ${p.catalogue_status==='broadcast'?'Broadcast collection':'Collected link · playback not newly verified'}</p>${flags[p.url]?`<p class="source-note">Your flag: ${esc(flags[p.url].reason)}</p>`:''}<div class="source-tags">${(p.seasonal_tags||[]).map(t=>`<span class="source-tag">${esc(labels[t]||t)}</span>`).join('')}</div>${p.notes?`<p class="source-note">${esc(p.notes)}</p>`:''}<details class="filename"><summary>File and seasonal fit</summary><p>${esc(p.filename||decodeURIComponent(new URL(p.url).pathname.split('/').pop()))}</p><p>${(p.schedule_months||[]).map(m=>monthNames[m-1]).join(', ')||'Not scheduled in this calendar'}</p>${p.holiday_events?.length?`<p>${esc(holidayPlacement(p))}</p>`:''}${p.scheduled_dates&&!p.holiday_events?.length?`<p>Scheduled dates: ${Object.entries(p.scheduled_dates).map(([m,days])=>esc(m.charAt(0).toUpperCase()+m.slice(1))+' '+days.slice(0,4).join(', ')+(days.length>4?'…':'')).join(' · ')}</p>`:''}${p.alternates?.length?`<p>${p.alternates.length} alternate source${p.alternates.length===1?'':'s'}</p>`:''}</details></div><div class="source-actions">${isHeld(p)?`<span class="source-note">HELD FOR REVIEW</span>`:`<a href="index.html?watch=${encodeURIComponent(p.url)}">WATCH ON TV</a>`}<a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">OPEN VIDEO</a><a href="${esc(p.source_page)}" target="_blank" rel="noopener noreferrer">ARCHIVE ITEM</a><button type="button" data-copy="${esc(p.url)}">COPY LINK</button><label class="small">Flag this source<select data-flag="${esc(p.url)}"><option value="">Choose issue…</option><option>Spanish or other non-English audio</option><option>Japanese without English subtitles</option><option>Broken or unplayable video</option><option value="clear">Clear my flag</option></select></label></div></article>`).join(''):'<p>No programmes match these filters. Try an Archive search above.</p>';$('show-more').hidden=shown.length>=filtered.length;}
function option(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o;}
async function init(){
 const params=new URLSearchParams(location.search);
 $('archive-form').addEventListener('submit',e=>{e.preventDefault();window.open(archiveURL($('archive-query').value,$('archive-scope').value),'_blank','noopener,noreferrer');});
 try{const r=await fetch('source-library.json?v=0352');if(!r.ok)throw Error('unavailable');const data=await r.json();programmes=data.programmes;
 [...new Set(programmes.flatMap(p=>p.channels||[p.channel]))].sort().forEach(ch=>$('library-channel').append(option(ch,ch)));
 [...new Set(programmes.flatMap(p=>p.seasonal_tags||[]))].sort((a,b)=>(labels[a]||a).localeCompare(labels[b]||b)).forEach(t=>$('library-tag').append(option(t,labels[t]||t)));
 monthNames.forEach((m,i)=>$('library-month').append(option(i+1,m)));
 ['query','channel','tag','month','language','status'].forEach(k=>{if(params.has(k))$('library-'+k).value=params.get(k);});
 $('search-presets').innerHTML=data.search_presets.map(p=>`<a href="${esc(archiveURL(p.query))}" target="_blank" rel="noopener noreferrer">${esc(p.label)}</a>`).join('');
 for(const id of ['library-query','library-channel','library-tag','library-month','library-language','library-status'])$(id).addEventListener(id==='library-query'?'input':'change',()=>{visible=40;render();});
 $('reset-filters').addEventListener('click',()=>{for(const id of ['library-query','library-channel','library-tag','library-month','library-language','library-status'])$(id).value='';visible=40;render();});$('show-more').addEventListener('click',()=>{visible+=40;render();});
 $('source-results').addEventListener('click',async e=>{const b=e.target.closest('[data-copy]');if(!b)return;try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='COPIED';}catch{b.textContent='SELECT LINK';const card=b.closest('article');const a=card.querySelector('a');a.textContent=b.dataset.copy;const range=document.createRange();range.selectNodeContents(a);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);}});
 $('source-results').addEventListener('change',e=>{const u=e.target.dataset.flag;if(!u||!e.target.value)return;if(e.target.value==='clear')delete flags[u];else flags[u]={url:u,title:programmes.find(p=>p.url===u)?.title,reason:e.target.value,reported_at:new Date().toISOString()};try{localStorage.setItem('bootleg.source.flags',JSON.stringify(flags));$('flag-feedback').textContent='Saved on this browser · '+Object.keys(flags).length+' flags. Reload the TV to apply holds.';}catch{$('flag-feedback').textContent='Browser storage unavailable; this flag is held only while this page stays open.';}render();});
 $('export-flags').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({flags:Object.values(flags)},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='Bootleg-Source-Flags.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
 render();
 }catch{$('source-count').textContent='Source library unavailable. Reload to try again.';}
}
init();
})(globalThis);
